version: '3.3' # 2버전과 3버전 차이가 많이 남

services:
  my_backend: #4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/my_backend/src
    env_file:
      - ./.env
    ports:
      - 3000:3000

  my_database: #2
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'flog'
      MYSQL_ROOT_PASSWORD: '1234'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    cap_add:
      - SYS_NICE
    ports: 
      - 3306:3306

  # my_redis: #5
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

  # elasticsearch: #1
  #   image: elasticsearch:7.17.0
  #   environment:
  #     discovery.type: single-node
  #   ports:
  #     - 9200:9200

  # # kibana:
  # #   image: kibana:7.17.0
  # #   environment:
  # #     ELASTICSERCH_UTL:http://elasticsearch:9200
  # #     ELASTICSERCH_HOSTS:http://elasticsearch:9200
  # #   ports:
  # #     - 5601:5601

  # logstash:
  #   image: logstash:7.17.0
  #   volumes:
  #     - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
